export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import ChakraWrapper from "./ChakraWrapper";
import TanstackQueryWrapper from "./TanstackQueryWrapper";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Create a client
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <TanstackQueryWrapper>
          <ChakraWrapper>{children}</ChakraWrapper>
        </TanstackQueryWrapper>
      </body>
    </html>
  );
}
